### PR TITLE
Updated dll

### PR DESCRIPTION
**Pull request by edvinalestig**
The new updated dll that I forgot to add.

### CODE REVIEW

**Comment by tony56a** [comment]
Sounds good. I've already built and uploaded the mod though, so please feel free to check if the feature is working on your end, thanks!

**Comment by edvinalestig** [comment]
It's all working on my end. The dll you uploaded was the one where I removed all the errors but didn't use the built-in methods to find IPT2, so it should be working for everyone.

**Comment by edvinalestig** [comment]
I found one thing. The button to turn passenger figures off seems to disappear when IPT2 is not loaded and changes place if it is loaded. The updated version works fine for me.

**Comment by tony56a** [comment]
Ah apologies, I added those changes so as to not have the option when the mods not there, and to not have the option when it's in editor mode.

**Pull request merged**
